.. |save-and-exit| image:: images/save-and-exit.png
   :height: 24px
   :class: no-scaled-link

.. |apply| image:: images/apply.png
   :height: 24px
   :class: no-scaled-link

.. |valid| image:: images/valid.png
   :height: 16px
   :class: no-scaled-link

.. |show-advanced-fields| image:: images/show-advanced-fields.png
   :height: 22px
   :class: no-scaled-link

.. |add-item| image:: images/add-item.png
   :height: 24px
   :class: no-scaled-link

.. |ready| image:: images/ready.png
   :height: 16px
   :class: no-scaled-link

.. |create-in-progress| image:: images/create-in-progress.png
   :height: 16px
   :class: no-scaled-link

.. |three-dots| image:: images/three-dots.png
   :height: 28px
   :class: no-scaled-link

.. |out-arrows| image:: images/out-arrows.png
   :height: 26px
   :class: no-scaled-link

.. |edit-mode| image:: images/edit-mode.png
   :height: 24px
   :class: no-scaled-link

.. |download-kubeconfig-button| image:: images/download-kubeconfig-buton.png
   :height: 20px
   :class: no-scaled-link

.. |intermediate-advanced| image:: images/intermediate-advanced.png
   :width: 100%
   :class: no-scaled-link

.. |login-url| image:: images/login-url.png
   :width: 100%
   :class: no-scaled-link

.. |accept-eula| image:: images/accept-eula.png
   :width: 100%
   :class: no-scaled-link

.. |personas| image:: images/personas.png
   :width: 100%
   :class: no-scaled-link

.. |logged-in| image:: images/logged-in.png
   :width: 100%
   :class: no-scaled-link
