.. |github_user| replace:: robinmordasiewicz
.. |github_version| replace:: main
.. |githuborgname| replace:: robinmordasiewicz
.. |githubrepo| replace:: f5-xc-iac
.. |githubrepobranch| replace:: site-name
.. |githubuseremail| replace:: email@example.com
.. |githubuserfullname| replace:: FirstName LastName
.. |githubusername| replace:: <your-github-account>
.. |workstationhostname| replace:: <workstation-hostname>
.. |workstationsshport| replace:: 22
.. |workstationusername| replace:: ubuntu
